CREATE DATABASE customer_shopping_behaviour;

USE customer_shopping_behaviour;
SELECT *
FROM customer;

# what is the total revenue generated by male v/s female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender;

#2 which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'YES' AND
purchase_amount >= (SELECT AVG(purchase_amount) FROM customer); 

#3 which are the top 5 products with the highest avegare review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) as avg_product_rating
FROM customer
GROUP BY item_purchased 
ORDER BY AVG(review_rating) DESC
LIMIT 5;

#4 compare the average purchase amount between standard and express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type IN ('standard', 'express')
GROUP BY  shipping_type;

#5 do subscribed customers spent more? compare average spend & total revenue between subscribers & non-subscribers.
SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as revenue
FROM customer
GROUP BY subscription_status
ORDER BY revenue, avg_spend DESC;

#6 which 5 products have the highest percentage of purchases with discounts appplied?
SELECT item_purchased, 
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) as discount_rate
FROM customer 
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

#7 segment customers into new, returning & loyal based on their total number of previous purchases & show the count of each segment.
WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE 
WHEN previous_purchases = 1 THEN  'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment
FROM customer
)

SELECT customer_segment, COUNT(*) AS no_of_segment
FROM customer_type
GROUP BY customer_segment;

#8 what are the top 3 most purchased products within each category?
WITH item_counts AS (
SELECT 
category, item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer 
GROUP BY category, item_purchased
)
SELECT category, item_purchased, total_orders, item_rank
FROM item_counts
WHERE item_rank <= 3;

#9 are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe.
SELECT COUNT(customer_id) as repeat_buyers, subscription_status
FROM customer 
WHERE previous_purchases > 5
GROUP BY subscription_status;

#10 what is the revenue contribution of each age group?
SELECT age, SUM(purchase_amount) as revenue 
FROM customer
GROUP BY age 
ORDER BY revenue DESC;